dynamodb:
  accessKey: AKIASEAB4D46RA46TIBV
  secretKey: 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
  region: eu-west-1

s3:
  accessKey: AKIASEAB4D46RA46TIBV
  secretKey: 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
  region: eu-west-2
  bucketName: jfl110-my-location
  fileName: test.squares.json
  photo:
    bucketName: jfl110-my-location
    photoFolderName: photos/live