name: Promote to Production & Deploy

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_2 }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_2 }}
          aws-region: eu-west-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Promote Staging Image to Production
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker pull $ECR_REGISTRY/jamesleach-dev:staging
          docker tag $ECR_REGISTRY/jamesleach-dev:staging $ECR_REGISTRY/jamesleach-dev:production
          docker push $ECR_REGISTRY/jamesleach-dev:production

      - name: Deploy to Production
        run: |
          aws ecs update-service --cluster="jamesleach-dev-ec2" --service="jamesleach-dev-production-ec2" --force-new-deployment
          aws ecs update-service --cluster="jamesleach-dev" --service="jamesleach-dev-production" --force-new-deployment