name: Promote to Production

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Promote Staging Image to Production
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
             docker tag $ECR_REGISTRY/jamesleach-dev:staging $ECR_REGISTRY/jamesleach-dev:production
             docker push $ECR_REGISTRY/jamesleach-dev:production